#!/bin/bash

module load freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
module load ants

#script directory

# study name and directory
export STUDY=temple
export SRCDIR=$HOME/analysis/temple
export STUDYDIR=$STOCKYARD2/ls6/temple
export BATCHDIR=$STOCKYARD2/ls6/temple/batch/launchscripts

# add analysis scripts to path
export PATH=$PATH:$SRCDIR/bin
export STUDYDIR=$STOCKYARD2/ls6/temple
. $STOCKYARD2/ls6/tempenv/bin/activate

# subjects
export SUBJNOS=024
export SUBIDS=temple_024
export BIDIDS=temple024

