#!/bin/bash

#script directory
module load freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
module load ants
# study name and directory
export STUDY=temple
export SRCDIR=$HOME/analysis/temple
export STUDYDIR=$STOCKYARD2/ls6/temple
export BATCHDIR=$STOCKYARD2/ls6/temple/batch/launchscripts
export FSDIR=$SCRATCH/temple/skyra_prepro/derivatives/fmriprep/sourcedata/freesurfer
export FMDIR=$SCRATCH/temple/skyra_prepro/derivatives/fmriprep
export CORR=/corral-repl/utexas/prestonlab/temple
# add analysis scripts to path
export PATH=$PATH:$SRCDIR/bin
export PATH=$PATH:$HOME/analysis/temple/rsa
export STUDYDIR=$STOCKYARD2/ls6/temple
. $HOME/analysis/temple/rsa/bin/activate

# subjects
export SUBJNOS=020:022:025:029:030:034:035:036:037:038:041:042:050:051
export SUBIDS=temple_020:temple022:temple025:temple029:temple030:temple034:temple035:temple036:temple037:temple038:temple041:temple042:temple050:temple051
export BIDIDS=temple016:temple019:temple020:temple022:temple024:temple025:temple029:temple030:temple032:temple033:temple034:temple035:temple036:temple037:temple038:temple041:temple042:temple045:temple050:temple051:temple053:temple056:temple057:temple058
export BIDIDSTEMP=temple016:temple019:temple020:temple022:temple024:temple025:temple029:temple030:temple032:temple033:temple034:temple035:temple036:temple037:temple038:temple041:temple042:temple045:temple050:temple053:temple056:temple057:temple058
